- id: ina219_ups_hat_on_power_loss
  alias: '[Hassio UPS] On Power Loss/Restored'
  description: Send notification on power loss
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.hassio_ups_online
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
    - binary_sensor.hassio_ups_online
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.hassio_ups_online
      state: 'off'
    then:
    - service: notify.notify
      data:
        message: Power outage detected
        title: "\U0001F50C *Hassio UPS*"
    else:
    - service: notify.notify
      data:
        message: Power restored
        title: "\U0001F50C *Hassio UPS*"
  mode: single
- id: ina219_ups_hat_on_charge_critical
  alias: '[Hassio UPS] On Charge Critical'
  description: Send notification & gracefully shutdown host
  trigger:
  - platform: numeric_state
    entity_id: sensor.hassio_ups_soc
    for:
      hours: 0
      minutes: 0
      seconds: 20
    below: 10
  action:
  - service: notify.notify
    data:
      message: Battery critical. Shutting down.
      title: "\U0001FAAB *Hassio UPS*"
  - event: set_shutdown_reason
    event_data:
      reason: ups_charge_critical
  - service: hassio.host_shutdown
    data: {}
    enabled: true
  mode: single